function [ MMbyidimstats, Runstats, MMsummary,MM,uidim ] = testMMmethodOct3( testcaseid )
%UNTITLED3 Summary of this function goes here
%   Detailed explanation goes here
if testcaseid == 1
    load('test1.mat','sample','idim');
    %NOTE: the above sample was generated from August15 code for 
    %ExampleUpdated using the parameters below. 
    % rgparam = 5; sampleparam = 800
    %[ sample,spheresample,linesample,samplesize ] = ExampleUpdated( sampleparam,rgparam);
    %The idim values were generated by the August 15 code for variancebaseidim

    data = sample;
    SVDbound = 3000;maxscale = 3;K = 3; varthresh = .95; eps = 10^(-14);
    testproportion = .4; runs = 20;seed = 5; confidencebound = .95;
    figs = 0; fname = 'tcid1';
    [MMbyidimstats, MMsummary,MM,uidim,Runstats ] = MMMethod(data,idim,testproportion,runs, seed,eps,SVDbound,maxscale,K,varthresh,confidencebound, figs,fname );
elseif testcaseid == 2
    dirname = '/Users/lindaness/Documents/MATLAB/wisdmreproducibility/results/';
    load([dirname,'test9-results.mat'],'data','idim');
    szdata = size(data)
    szidim = size(idim)
    SVDbound = 400;maxscale = 3;K = 3; varthresh = .95; eps = 10^(-14);
    testproportion = .4; runs = 1;seed = 5; confidencebound = .95;
    figs = 0; fname = 'MMmethodtest2';
    [ MMsummary,MM,u ] = MultiManifold(data,idim,SVDbound,maxscale,K, varthresh,eps)
    %[MMbyidimstats, MMsummary,MM,uidim,Runstats ] = MMMethod(data,idim,testproportion,runs, seed,eps,SVDbound,maxscale,K,varthresh,confidencebound, figs,fname );
     
    
end
end

